name: github-actions
on: [workflow_dispatch, pull_request]
jobs:
  check-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run Check Static
        run: yarn check
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run Unit Test
        run: yarn test:unit
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run Build
        run: yarn build
        env:
          NEXT_PUBLIC_API_URL: https://next-13-ecru.vercel.app/api
